#!/usr/bin/env python3
"""Build the distributable one-shot ZIP from this package directory.

Usage: python scripts/make_zip.py [output.zip]
Excludes runtime/local artifacts and regenerates FILE_MANIFEST.md.
"""
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG_NAME = "LoL_AI_Master_Orchestrator_V4"

EXCLUDE_DIRS = {".git", ".venv", ".orchestrator", "__pycache__", ".pytest_cache",
                "node_modules"}
EXCLUDE_FILES = {"ONE_SHOT_REPORT.md", "PROJECT_STATE.md", "CURRENT_TASK.md"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo", ".zip"}
# runtime dirs ship empty except a keep marker
RUNTIME_DIRS = ["state", "reports/human-gates", "reports/acceptance"]


def iter_files():
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        parts = rel.parts
        if any(part in EXCLUDE_DIRS for part in parts):
            continue
        if rel.name in EXCLUDE_FILES or p.suffix in EXCLUDE_SUFFIXES:
            continue
        if any(str(rel).replace("\\", "/").startswith(d + "/") for d in RUNTIME_DIRS):
            continue
        yield rel


def main():
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / f"{PKG_NAME}_OneShot.zip"
    files = list(iter_files())

    manifest = [f"# FILE MANIFEST — {PKG_NAME} (generated by scripts/make_zip.py)", ""]
    manifest += [f"- `{rel.as_posix()}`" for rel in files]
    (ROOT / "FILE_MANIFEST.md").write_text("\n".join(manifest) + "\n", encoding="utf-8")
    if Path("FILE_MANIFEST.md") not in files:
        files.append(Path("FILE_MANIFEST.md"))

    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for rel in files:
            arcname = f"{PKG_NAME}/{rel.as_posix()}"
            zi = zipfile.ZipInfo.from_file(ROOT / rel, arcname)
            # ensure the shell launcher extracts executable on Linux/macOS
            # (otherwise `./start.sh` fails with 'Permission denied')
            if rel.name.endswith(".sh"):
                zi.external_attr = (0o755 << 16)
            zi.compress_type = zipfile.ZIP_DEFLATED
            with open(ROOT / rel, "rb") as fh:
                z.writestr(zi, fh.read())
        for d in RUNTIME_DIRS:
            z.writestr(f"{PKG_NAME}/{d}/.gitkeep", "")
    print(f"wrote {out} ({out.stat().st_size / 1024:.0f} KiB, {len(files)} files)")


if __name__ == "__main__":
    main()
