"""Canonical state store.

state/project_state.json is the single source of truth. PROJECT_STATE.md
and CURRENT_TASK.md are generated projections and never read back.
Writes are atomic (tmp + fsync + os.replace) so a crash can never leave
a half-written canonical state. Every transition goes through
gates.validate_lifecycle_transition — there is no code path that writes
an illegal lifecycle.
"""
import json, os
from pathlib import Path

from . import gates
from .models import Lifecycle

REQUIRED_KEYS = (
    "schema_version", "run_id", "sequence", "phase_id", "lifecycle", "attempt",
    "builder", "candidate_commit", "test_evidence_id", "review_evidence_id",
    "human_gate_required", "last_gate", "reviewer_provider", "builder_provider",
    "approved_commit", "reviewed_commit", "tested_commit", "merged_commit",
    "human_approval_id",
)


class StateError(Exception):
    pass


def _atomic_write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


class StateStore:
    def __init__(self, state_path, *, journal=None, current_task_path=None,
                 state_md_path=None, task_md_path=None):
        self.state_path = Path(state_path)
        self.journal = journal
        self.current_task_path = Path(current_task_path) if current_task_path else None
        self.state_md_path = Path(state_md_path) if state_md_path else None
        self.task_md_path = Path(task_md_path) if task_md_path else None

    # --- load ------------------------------------------------------------
    def load(self):
        try:
            raw = self.state_path.read_text(encoding="utf-8")
        except FileNotFoundError as e:
            raise StateError("canonical state file missing") from e
        try:
            st = json.loads(raw)
        except json.JSONDecodeError as e:
            raise StateError(f"canonical state JSON invalid: {e}") from e
        if not isinstance(st, dict):
            raise StateError("canonical state is not an object")
        missing = [k for k in REQUIRED_KEYS if k not in st]
        if missing:
            raise StateError("canonical state schema incomplete: missing " + ", ".join(missing))
        if st["schema_version"] != 2:
            raise StateError(f"unsupported state schema_version: {st['schema_version']}")
        if st["lifecycle"] not in set(Lifecycle):
            raise StateError(f"unknown lifecycle: {st['lifecycle']}")
        if not isinstance(st["sequence"], int) or st["sequence"] < 0:
            raise StateError("sequence must be a non-negative integer")
        return st

    # --- save ------------------------------------------------------------
    def save(self, st, *, task_note=""):
        st = dict(st)
        st["sequence"] = int(st["sequence"]) + 1
        _atomic_write(self.state_path, json.dumps(st, indent=2, sort_keys=False))
        self._project(st, task_note)
        return st

    def _project(self, st, task_note):
        if self.current_task_path:
            _atomic_write(self.current_task_path, json.dumps({
                "phase_id": st["phase_id"],
                "lifecycle": st["lifecycle"],
                "run_id": st["run_id"],
                "task": task_note or f"phase {st['phase_id']} in {st['lifecycle']}",
                "generated_from_project_state": True,
            }, indent=2))
        if self.state_md_path:
            _atomic_write(self.state_md_path,
                          "# PROJECT STATE\n\nGenerated by orchestrator. Do not edit manually.\n\n"
                          "```json\n" + json.dumps(st, indent=2) + "\n```\n")
        if self.task_md_path:
            _atomic_write(self.task_md_path,
                          "# CURRENT TASK\n\nGenerated by orchestrator. Do not edit manually.\n\n"
                          f"- phase: `{st['phase_id']}`\n- lifecycle: `{st['lifecycle']}`\n"
                          f"- run: `{st['run_id']}`\n- note: {task_note or '-'}\n")

    # --- transitions -----------------------------------------------------
    def transition(self, st, phase_cfg, to, *, reason=None, task_note="", **updates):
        """The only way lifecycle changes. Validates legality first
        (fail closed), then persists atomically and journals the event."""
        frm = st["lifecycle"]
        decision = gates.validate_lifecycle_transition(
            phase_cfg, lifecycle_from=frm, lifecycle_to=to)
        if not decision.passed:
            raise StateError("; ".join(decision.reasons))
        st = dict(st)
        st["lifecycle"] = to
        st.update(updates)
        st = self.save(st, task_note=task_note)
        if self.journal:
            self.journal.append("lifecycle_transition", phase_id=st["phase_id"],
                                run_id=st["run_id"], frm=frm, to=to,
                                sequence=st["sequence"], reason=reason)
        return st
